#ifndef __OPENWM__INPUT__KEY_H_
#define __OPENWM__INPUT__KEY_H_ 1

#include <stdint.h>

typedef uint8_t openwm_key_state_t;
typedef uint16_t openwm_key_t;

#define KEY_STATE_NONE      (openwm_key_state_t)0
#define KEY_STATE_PRESS     (openwm_key_state_t)1
#define KEY_STATE_REPEAT    (openwm_key_state_t)2
#define KEY_STATE_RELEASE   (openwm_key_state_t)3

#define KEY_FIRST           KEY_SPACE
#define KEY_SPACE           (openwm_key_t)0
#define KEY_APOSTROPHE      (openwm_key_t)1
#define KEY_COMMA           (openwm_key_t)2
#define KEY_MINUS           (openwm_key_t)3
#define KEY_PERIOD          (openwm_key_t)4
#define KEY_SLASH           (openwm_key_t)5
#define KEY_A               (openwm_key_t)6
#define KEY_B               (openwm_key_t)7
#define KEY_C               (openwm_key_t)8
#define KEY_D               (openwm_key_t)9
#define KEY_E               (openwm_key_t)10
#define KEY_F               (openwm_key_t)11
#define KEY_G               (openwm_key_t)12
#define KEY_H               (openwm_key_t)13
#define KEY_I               (openwm_key_t)14
#define KEY_J               (openwm_key_t)15
#define KEY_K               (openwm_key_t)16
#define KEY_L               (openwm_key_t)17
#define KEY_M               (openwm_key_t)18
#define KEY_N               (openwm_key_t)19
#define KEY_O               (openwm_key_t)20
#define KEY_P               (openwm_key_t)21
#define KEY_Q               (openwm_key_t)22
#define KEY_R               (openwm_key_t)23
#define KEY_S               (openwm_key_t)24
#define KEY_T               (openwm_key_t)25
#define KEY_U               (openwm_key_t)26
#define KEY_V               (openwm_key_t)27
#define KEY_W               (openwm_key_t)28
#define KEY_X               (openwm_key_t)29
#define KEY_Y               (openwm_key_t)30
#define KEY_Z               (openwm_key_t)31
#define KEY_NUM0            (openwm_key_t)32
#define KEY_NUM1            (openwm_key_t)33
#define KEY_NUM2            (openwm_key_t)34
#define KEY_NUM3            (openwm_key_t)35
#define KEY_NUM4            (openwm_key_t)36
#define KEY_NUM5            (openwm_key_t)37
#define KEY_NUM6            (openwm_key_t)38
#define KEY_NUM7            (openwm_key_t)39
#define KEY_NUM8            (openwm_key_t)40
#define KEY_NUM9            (openwm_key_t)41
#define KEY_SEMICOLON       (openwm_key_t)42
#define KEY_EQUAL           (openwm_key_t)43
#define KEY_LEFT_BRACKET    (openwm_key_t)44
#define KEY_RIGHT_BRACKET   (openwm_key_t)45
#define KEY_BACKSLASH       (openwm_key_t)46
#define KEY_GRAVE_ACCENT    (openwm_key_t)47
#define KEY_ESCAPE          (openwm_key_t)48
#define KEY_ENTER           (openwm_key_t)49
#define KEY_TAB             (openwm_key_t)50
#define KEY_BACKSPACE       (openwm_key_t)51
#define KEY_INSERT          (openwm_key_t)52
#define KEY_DEL             (openwm_key_t)53
#define KEY_RIGHT           (openwm_key_t)54
#define KEY_LEFT            (openwm_key_t)55
#define KEY_DOWN            (openwm_key_t)56
#define KEY_UP              (openwm_key_t)57
#define KEY_PAGE_DOWN       (openwm_key_t)58
#define KEY_PAGE_UP         (openwm_key_t)59
#define KEY_HOME            (openwm_key_t)60
#define KEY_END             (openwm_key_t)61
#define KEY_CAPS_LOCK       (openwm_key_t)62
#define KEY_SCROLL_LOCK     (openwm_key_t)63
#define KEY_NUM_LOCK        (openwm_key_t)64
#define KEY_PRINT_SCREEN    (openwm_key_t)65
#define KEY_PAUSE           (openwm_key_t)66
#define KEY_F1              (openwm_key_t)67
#define KEY_F2              (openwm_key_t)68
#define KEY_F3              (openwm_key_t)69
#define KEY_F4              (openwm_key_t)70
#define KEY_F5              (openwm_key_t)71
#define KEY_F6              (openwm_key_t)72
#define KEY_F7              (openwm_key_t)73
#define KEY_F8              (openwm_key_t)74
#define KEY_F9              (openwm_key_t)75
#define KEY_F10             (openwm_key_t)76
#define KEY_F11             (openwm_key_t)77
#define KEY_F12             (openwm_key_t)78
#define KEY_F13             (openwm_key_t)79
#define KEY_F14             (openwm_key_t)80
#define KEY_F15             (openwm_key_t)81
#define KEY_F16             (openwm_key_t)82
#define KEY_F17             (openwm_key_t)83
#define KEY_F18             (openwm_key_t)84
#define KEY_F19             (openwm_key_t)85
#define KEY_F20             (openwm_key_t)86
#define KEY_F21             (openwm_key_t)87
#define KEY_F22             (openwm_key_t)88
#define KEY_F23             (openwm_key_t)89
#define KEY_F24             (openwm_key_t)90
#define KEY_F25             (openwm_key_t)91
#define KEY_LEFT_SHIFT      (openwm_key_t)92
#define KEY_LEFT_CONTROL    (openwm_key_t)93
#define KEY_LEFT_ALT        (openwm_key_t)94
#define KEY_LEFT_SUPER      (openwm_key_t)95
#define KEY_RIGHT_SHIFT     (openwm_key_t)96
#define KEY_RIGHT_CONTROL   (openwm_key_t)97
#define KEY_RIGHT_ALT       (openwm_key_t)98
#define KEY_RIGHT_SUPER     (openwm_key_t)99
#define KEY_MENU            (openwm_key_t)100
#define KEY_KP_0            (openwm_key_t)101
#define KEY_KP_1            (openwm_key_t)102
#define KEY_KP_2            (openwm_key_t)103
#define KEY_KP_3            (openwm_key_t)104
#define KEY_KP_4            (openwm_key_t)105
#define KEY_KP_5            (openwm_key_t)106
#define KEY_KP_6            (openwm_key_t)107
#define KEY_KP_7            (openwm_key_t)108
#define KEY_KP_8            (openwm_key_t)109
#define KEY_KP_9            (openwm_key_t)110
#define KEY_KP_DECIMAL      (openwm_key_t)111
#define KEY_KP_DIVIDE       (openwm_key_t)112
#define KEY_KP_MULTIPLY     (openwm_key_t)113
#define KEY_KP_SUBTRACT     (openwm_key_t)114
#define KEY_KP_ADD          (openwm_key_t)115
#define KEY_KP_ENTER        (openwm_key_t)116
#define KEY_KP_EQUAL        (openwm_key_t)117
#define KEY_LAST            KEY_KP_EQUAL

openwm_key_state_t openwm_keyboard_get_key(openwm_key_t key);

#endif