#ifndef __OPENWM__INPUT__KEY_H_
#define __OPENWM__INPUT__KEY_H_ 1

#include <stdint.h>

typedef uint8_t openwm_key_state_t;
typedef uint16_t openwm_key_t;

#define OPENWM_KEY_STATE_NONE      (openwm_key_state_t)0
#define OPENWM_KEY_STATE_PRESS     (openwm_key_state_t)1
#define OPENWM_KEY_STATE_REPEAT    (openwm_key_state_t)2
#define OPENWM_KEY_STATE_RELEASE   (openwm_key_state_t)3

#define OPENWM_KEY_FIRST           OPENWM_KEY_SPACE
#define OPENWM_KEY_SPACE           (openwm_key_t)0
#define OPENWM_KEY_APOSTROPHE      (openwm_key_t)1
#define OPENWM_KEY_COMMA           (openwm_key_t)2
#define OPENWM_KEY_MINUS           (openwm_key_t)3
#define OPENWM_KEY_PERIOD          (openwm_key_t)4
#define OPENWM_KEY_SLASH           (openwm_key_t)5
#define OPENWM_KEY_A               (openwm_key_t)6
#define OPENWM_KEY_B               (openwm_key_t)7
#define OPENWM_KEY_C               (openwm_key_t)8
#define OPENWM_KEY_D               (openwm_key_t)9
#define OPENWM_KEY_E               (openwm_key_t)10
#define OPENWM_KEY_F               (openwm_key_t)11
#define OPENWM_KEY_G               (openwm_key_t)12
#define OPENWM_KEY_H               (openwm_key_t)13
#define OPENWM_KEY_I               (openwm_key_t)14
#define OPENWM_KEY_J               (openwm_key_t)15
#define OPENWM_KEY_K               (openwm_key_t)16
#define OPENWM_KEY_L               (openwm_key_t)17
#define OPENWM_KEY_M               (openwm_key_t)18
#define OPENWM_KEY_N               (openwm_key_t)19
#define OPENWM_KEY_O               (openwm_key_t)20
#define OPENWM_KEY_P               (openwm_key_t)21
#define OPENWM_KEY_Q               (openwm_key_t)22
#define OPENWM_KEY_R               (openwm_key_t)23
#define OPENWM_KEY_S               (openwm_key_t)24
#define OPENWM_KEY_T               (openwm_key_t)25
#define OPENWM_KEY_U               (openwm_key_t)26
#define OPENWM_KEY_V               (openwm_key_t)27
#define OPENWM_KEY_W               (openwm_key_t)28
#define OPENWM_KEY_X               (openwm_key_t)29
#define OPENWM_KEY_Y               (openwm_key_t)30
#define OPENWM_KEY_Z               (openwm_key_t)31
#define OPENWM_KEY_NUM0            (openwm_key_t)32
#define OPENWM_KEY_NUM1            (openwm_key_t)33
#define OPENWM_KEY_NUM2            (openwm_key_t)34
#define OPENWM_KEY_NUM3            (openwm_key_t)35
#define OPENWM_KEY_NUM4            (openwm_key_t)36
#define OPENWM_KEY_NUM5            (openwm_key_t)37
#define OPENWM_KEY_NUM6            (openwm_key_t)38
#define OPENWM_KEY_NUM7            (openwm_key_t)39
#define OPENWM_KEY_NUM8            (openwm_key_t)40
#define OPENWM_KEY_NUM9            (openwm_key_t)41
#define OPENWM_KEY_SEMICOLON       (openwm_key_t)42
#define OPENWM_KEY_EQUAL           (openwm_key_t)43
#define OPENWM_KEY_LEFT_BRACKET    (openwm_key_t)44
#define OPENWM_KEY_RIGHT_BRACKET   (openwm_key_t)45
#define OPENWM_KEY_BACKSLASH       (openwm_key_t)46
#define OPENWM_KEY_GRAVE_ACCENT    (openwm_key_t)47
#define OPENWM_KEY_ESCAPE          (openwm_key_t)48
#define OPENWM_KEY_ENTER           (openwm_key_t)49
#define OPENWM_KEY_TAB             (openwm_key_t)50
#define OPENWM_KEY_BACKSPACE       (openwm_key_t)51
#define OPENWM_KEY_INSERT          (openwm_key_t)52
#define OPENWM_KEY_DEL             (openwm_key_t)53
#define OPENWM_KEY_RIGHT           (openwm_key_t)54
#define OPENWM_KEY_LEFT            (openwm_key_t)55
#define OPENWM_KEY_DOWN            (openwm_key_t)56
#define OPENWM_KEY_UP              (openwm_key_t)57
#define OPENWM_KEY_PAGE_DOWN       (openwm_key_t)58
#define OPENWM_KEY_PAGE_UP         (openwm_key_t)59
#define OPENWM_KEY_HOME            (openwm_key_t)60
#define OPENWM_KEY_END             (openwm_key_t)61
#define OPENWM_KEY_CAPS_LOCK       (openwm_key_t)62
#define OPENWM_KEY_SCROLL_LOCK     (openwm_key_t)63
#define OPENWM_KEY_NUM_LOCK        (openwm_key_t)64
#define OPENWM_KEY_PRINT_SCREEN    (openwm_key_t)65
#define OPENWM_KEY_PAUSE           (openwm_key_t)66
#define OPENWM_KEY_F1              (openwm_key_t)67
#define OPENWM_KEY_F2              (openwm_key_t)68
#define OPENWM_KEY_F3              (openwm_key_t)69
#define OPENWM_KEY_F4              (openwm_key_t)70
#define OPENWM_KEY_F5              (openwm_key_t)71
#define OPENWM_KEY_F6              (openwm_key_t)72
#define OPENWM_KEY_F7              (openwm_key_t)73
#define OPENWM_KEY_F8              (openwm_key_t)74
#define OPENWM_KEY_F9              (openwm_key_t)75
#define OPENWM_KEY_F10             (openwm_key_t)76
#define OPENWM_KEY_F11             (openwm_key_t)77
#define OPENWM_KEY_F12             (openwm_key_t)78
#define OPENWM_KEY_F13             (openwm_key_t)79
#define OPENWM_KEY_F14             (openwm_key_t)80
#define OPENWM_KEY_F15             (openwm_key_t)81
#define OPENWM_KEY_F16             (openwm_key_t)82
#define OPENWM_KEY_F17             (openwm_key_t)83
#define OPENWM_KEY_F18             (openwm_key_t)84
#define OPENWM_KEY_F19             (openwm_key_t)85
#define OPENWM_KEY_F20             (openwm_key_t)86
#define OPENWM_KEY_F21             (openwm_key_t)87
#define OPENWM_KEY_F22             (openwm_key_t)88
#define OPENWM_KEY_F23             (openwm_key_t)89
#define OPENWM_KEY_F24             (openwm_key_t)90
#define OPENWM_KEY_F25             (openwm_key_t)91
#define OPENWM_KEY_LEFT_SHIFT      (openwm_key_t)92
#define OPENWM_KEY_LEFT_CONTROL    (openwm_key_t)93
#define OPENWM_KEY_LEFT_ALT        (openwm_key_t)94
#define OPENWM_KEY_LEFT_SUPER      (openwm_key_t)95
#define OPENWM_KEY_RIGHT_SHIFT     (openwm_key_t)96
#define OPENWM_KEY_RIGHT_CONTROL   (openwm_key_t)97
#define OPENWM_KEY_RIGHT_ALT       (openwm_key_t)98
#define OPENWM_KEY_RIGHT_SUPER     (openwm_key_t)99
#define OPENWM_KEY_MENU            (openwm_key_t)100
#define OPENWM_KEY_KP_0            (openwm_key_t)101
#define OPENWM_KEY_KP_1            (openwm_key_t)102
#define OPENWM_KEY_KP_2            (openwm_key_t)103
#define OPENWM_KEY_KP_3            (openwm_key_t)104
#define OPENWM_KEY_KP_4            (openwm_key_t)105
#define OPENWM_KEY_KP_5            (openwm_key_t)106
#define OPENWM_KEY_KP_6            (openwm_key_t)107
#define OPENWM_KEY_KP_7            (openwm_key_t)108
#define OPENWM_KEY_KP_8            (openwm_key_t)109
#define OPENWM_KEY_KP_9            (openwm_key_t)110
#define OPENWM_KEY_KP_DECIMAL      (openwm_key_t)111
#define OPENWM_KEY_KP_DIVIDE       (openwm_key_t)112
#define OPENWM_KEY_KP_MULTIPLY     (openwm_key_t)113
#define OPENWM_KEY_KP_SUBTRACT     (openwm_key_t)114
#define OPENWM_KEY_KP_ADD          (openwm_key_t)115
#define OPENWM_KEY_KP_ENTER        (openwm_key_t)116
#define OPENWM_KEY_KP_EQUAL        (openwm_key_t)117
#define OPENWM_KEY_LAST            OPENWM_KEY_KP_EQUAL

/*
 * Get the state of a key
*/
openwm_key_state_t openwm_keyboard_get_key(openwm_key_t key);

#endif